registration_shared_secret: ENC[AES256_GCM,data:Go9RfW1gqTXPFWeUWTSDCP+s6/5YRrSyIsB9/LDVs7QJw2WhFEpUR44TtkKnHZFqb6Dpxhd57b3WBfHw8BYWFVTxFNdeuBcl8OVMjaiGQMnxZrlOKONAt61QDEs7jetx4rQBjjefERGoJmAxbWUlEl5T7QJwzDaEElN0SFMG2JVld5qsW1iCPQMn+yzcEpUAihbmVONTee8EQ5b13abS03YNzE4y/4pbjPxhyyyhNEaOUiF00dBr/AiRPO0MjjLawP/xmCSZbL7T+1ifIUb0Kye+M5dN3tIDrf39Y7amlUh3h384+1UbG9BsBNg6MhBqaUDAaEIQdZzRVPyWszTMgw==,iv:L6fdrwHct4dGGktm3hap4D/HNjwORRTV/3STI5cewRY=,tag:OU/qF8CVXP43GMbeg8/Vmw==,type:str]
turn_shared_secret: ENC[AES256_GCM,data:nZ6jR0RQNo6kweYzpfnecLwoQTPlgpuwnva1xKsodRyq29v8Alu7msjL/SErwptW2NSRLSNVgYAYRrHcwx36Iw==,iv:SVaeMMgBtEJmwMa8fh90CQRNpqmNEgVhYAmXKi7E9tE=,tag:Z2OS0dNv/BuqQOmCJkzhfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbkxEZEMra3NOQjRZRWpX
            OEJGd2JIK1IzM3V4MW5mSGxvZE5xUTBJYUM4ClZHdlh6ZVhyQ3pHeGgxcmJJTERH
            L2pmSXdCd3JjcHk1N0l5UmY4Y3QyQWsKLS0tIGRHbmVTZzEzNDRiTHE5NElkOTgv
            c3M4RFc1YlZaNTFMTmU1SmVpS3pNakEK30O7hTTnwZDzdEKiryC1PqWJ0tLBOpF3
            z7UGbnb8BIjwCjEXRJ56ziRc2eb+WWK1ZChRZFsGzuAL1SzVAkJwtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m4rcl2y5xafgruq5ecwa67nwjgh3yv7r9795mke3jzyfwf5gv4asafvx2r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM1hCclhLcVV5YnRwbGxt
            cTZKdzE0c2ZWbE5SeVVwdExHWWdHZXBJMDNJCnJhcm1qZDRIbE1iRkNqNjdtQ3FM
            MnFLT2wwTDEyZCtud3ZsWG5FZlAvOFUKLS0tIGFFOXkyT2VYcER3MktTOW5RcXFB
            Nmk4cnA2UEhZeVBBYzdDUmtjcHRST3cKlKf9gAD8YGL1ZVcjscc5517hnPu1/Z8i
            Z3CQXd99MwBtJmywS5+TTX7oqyRX2h0Ahqk9gvta8+UqCmFsOyMcNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mm4um3f4wp0gx3e5u9zkdhx63n9wzvpnkg4k0azd8wvzg37vt45qpyqxc0
    lastmodified: "2026-09-02T06:46:08Z"
    mac: ENC[AES256_GCM,data:+EjP2/ARLcdtL7IljjDFWuGe/A+XHuAcv7nfM9IVCG6Udj8xS50Onzj4aqilwtC1kjUPki2yW+7tkemqKufJD9wz3JSF7kkv68FvcR9rATYcXGDxeq3ElFSQNqhxuOppG8yVaRBVCm5XvoD0QbpnAGfVkAWu0ic6SbUEesnSexU=,iv:5UKHG8m0LHmO3e8/XcvMeQriBXMgvhhL3dSuxqg0WQ0=,tag:INm3Ecx9Ltr7+jKSnHkBhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
