admin_password: ENC[AES256_GCM,data:dlkaYiAx9idtvSIur48=,iv:B0DQLYFF5AAaiF5K9DQislrB8hanpjEi2tq9yJaRMww=,tag:0I85I3b5mDwuThY1dHRGsw==,type:str]
secret_key: ENC[AES256_GCM,data:I+8x+EKDvob6SRSuTbVOW1aWngpAvlYBmyzfruB8trK7lYLfzyezBuu3AZ3iHkgRJgZ8Juol/MdCUK/ENjfGhA==,iv:msvlFmZu1s8aDO2JodWw2C3jIhra74C03omd9/JEqaM=,tag:MvutSjHTkz0nambNSrfp9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdnFBUTNVbDlhSDBKZTVt
            aENRdktFT2R3Znp1RVBoaG1aTU5FZTRGckNVCnYzcXBXRGVySUtqbFZldlArWnQv
            MEFidU8zTFhhRFE5TEhGdEE2QnNlNHMKLS0tIC93cGx6dERBeU9uYnlXK2N5ODAz
            L01QZUc4Wk1LTUZsZDhhYzREc3h0WkEKsx1aZiOu40kE6/fpAG3BBUBGrKIlbQjr
            nFkHKfj53yeakBXITCMmJaVvEc7N8v+A3MLE/HZKDwiCQJ0YAEIe2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m4rcl2y5xafgruq5ecwa67nwjgh3yv7r9795mke3jzyfwf5gv4asafvx2r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb252WW1kOUM3ajlSUFNx
            VU9QQldLZU1kbGlFeEROblFtY1FyRUxXREVFCmoxSi9HTmIwRE43dlh6Z2xudlNQ
            KzZMR1VPVEJDUXBqQWYxdExtY1FBc28KLS0tIGZTWnM5VGZyRVlMNmhxMkR6YklZ
            NDZkR3JuL3Z3bGJJQnliYUFLQ1FjdVUKiAWd9yxzZ9D8z5E/7m2B0RmbQVM8WsRA
            v+3sXalDgVnKWovT4Mu5wxne6+ZY1SrZQt1NcgXmPhAc4G4Ny4+m8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mm4um3f4wp0gx3e5u9zkdhx63n9wzvpnkg4k0azd8wvzg37vt45qpyqxc0
    lastmodified: "2026-09-01T11:52:24Z"
    mac: ENC[AES256_GCM,data:B5HjnNVKCyhtn4iAif5p/ir40aCq5wpgkma5UXL+HtQLCQJRtUtGWMnSvnY5cWjMjshZ5ASAD3NuaYmaeckXc7uybT58odrnJ+fy5hqpWCTY44mwfupK1i4Y300hRYcS/7kmZMCIfdE5ZioUGKHx5jgXL8VHkIhr2lMEpfgv9bc=,iv:VkguCMhFgX9Ja9LPBcDqdF7xFUzkMdIH0usKMR62LxU=,tag:gJJXJESEu3zPqP+1YV9BgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
