CREATE TABLE IF NOT EXISTS @schema@.todos (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz
);

insert into
  @schema@.todos (task)
values
  ('finish tutorial 0'),
  ('pat self on back');

GRANT ALL ON @schema@.todos to @role@;
